### ISSUE TITLE
Support for Spring Security 4

### ISSUE THREAD

**Issue by restfulhead** [ddtxra/spring-security-auth0#7]
Hi there,

Are you planning to add support for Spring Security 4? 

The current version fails with the following error:
`Configuration problem: You cannot use a spring-security-2.0.xsd or spring-security-3.0.xsd or spring-security-3.1.xsd schema or spring-security-3.2.xsd schema with Spring Security 4.0. Please update your schema declarations to the 4.0 schema.
Offending resource: class path resource [auth0-security-context.xml]`

Thanks
Patrick

**Comment by ddtxra** [comment]
Hello @ruhkopf ,
Thanks for reporting this issue. Spring Security 4 was not released when I developed this module.

Meanwhile this repository was forked by the auth0 team and is now maintained by them: 
- https://github.com/auth0/spring-security-auth0

You should open your issue there or simply make a pull request if you manage to fix the issue.

In any case along the year, we plan to migrate to Spring 4 as well and I will look more carefully into this.

Best regards and happy new year,
Daniel
