### ISSUE TITLE
Authorization Spring Security 

### ISSUE THREAD

**Issue by houssemzaier** [ddtxra/spring-security-auth0#8]
Is there any way to protect API resources  like using this code: @PreAuthorize("hasRole('ROLE_Admin')")

**Comment by ddtxra** [comment]
Yes, you can use authorization annotation-based if roles are added in Auth0.
https://github.com/ddtxra/spring-security-auth0/blob/master/spring-auth0-core/src/main/java/sib/calipho/spring/security/auth0/Auth0UserDetails.java#L46

If roles are coming from other service you may need to implement your own UserDetailsService.
