### ISSUE TITLE
exposed client secret

### ISSUE THREAD

**Issue by grandadmiralmcb** [ddtxra/spring-security-auth0#9]
auth0.properties file seems to have an exposed client secret.

**Comment by ddtxra** [comment]
Thanks for your message @grandadmiralmcb, 
The exposed client secret WU9VUl9TRUNSRVRfSUQ= in base64 corresponds to YOUR_SECRET_ID in ascii. It is used for testing and needs to be base64 to work, but it is not a real client auth0 secret id.
